### ISSUE TITLE
unable to display alert in status menu

### ISSUE THREAD

**Issue by or97140** [sveinbjornt/Platypus#107]
I'm creating a status menu app.  If an error occurs in the main function that builds the menu, I'd like to raise an alert pop-up.  I'm currently trapping the exception and printing it with "ALERT:error|<formatted stack trace>", but this is just printing the stack trace into the menu instead of giving me a modal alert.  I tried disabling "Run in Background" option on the Status Menu as well but got the same behavior.  Changing the interface to Text Window, I get the alert as expected.

**Comment by sveinbjornt** [comment]
The status menu output mode is different from the other ones since it waits for the script to finish before using/parsing the text output, and doesn't look for the ALERT: syntax. Why not simply catch your exception and print the error to stdout as red text or something? It's not really a good idea to trigger a modal alert immediately when someone opens a menu. At any rate, it's almost certainly a violation of Apple's Human Interface Guidelines.

**Comment by or97140** [comment]
Thanks for your response.  I got something working using osascript to display a dialog.
