### ISSUE TITLE
platypus file not reading new script changes

### ISSUE THREAD

**Issue by josh-flori** [sveinbjornt/Platypus#134]
If the platypus file is running test.py, which looks like this:

print(1)

it works. If I then go into test.py and edit it in any way whatsoever, for instance changing it to

print(1)
print(2)

then when I run the platypus file it will still run the first version of test.py. It's almost like the platypus file compiles the first script and stores it, running only that stored version in the future. I have tried several scripts with several changes on several platypus files and it only ever runs the version of the script that existed when the playtpus file was first created. Is this default behavior? I don't see it in the readme. How do I get it to read updated scripts?

I'm on high sierra 10.13.6.

This is my first issue sorry if I have done anything wrong.

**Comment by sveinbjornt** [comment]
Each time you create a Platypus app, your script is copied into the resulting application bundle. If you change the script, you need to recreate the app. If you want to continue editing the original script file and have the changes automatically apply to the app, try the "Create symlink to script and bundled" option when creating the app. This creates a symbolic link inside the application bundle to your script instead of copying it over.
