### ISSUE TITLE
Feature Request: run on exit

### ISSUE THREAD

**Issue by RwbyChan** [sveinbjornt/Platypus#136]
Hi there

I made a program that will start MySQL server and PHP server, now my issue is that if I close the app, the MySQL server is still running as it needs another command to stop it, would it be possible to add a feature so we can add a script that has to run on exit?

**Comment by cylott** [comment]
What scripting language/code are you using to start the server? You should be able to leave it as a running process so quitting the app will kill the process.

**Comment by sveinbjornt** [comment]
Platypus apps send a SIGTERM signal to the script process when the app is quit. What you want is best accomplished by handling the signal in the app itself, e.g:

https://raymii.org/s/snippets/Bash_Bits_Trap_Control_C_SIGTERM.html

**Comment by michaelherger** [comment]
My script usually would exit whenever it's called. Similarly to the reporter I would start some background tasks, then exit. Would you recommend to keep the script running all the time?

I have a menu bar item. That script is called whenever I click the icon. How would I then distinguish between initial call and subsequent calls of the script due to the click of the icon?
