### ISSUE TITLE
Hiding python source code

### ISSUE THREAD

**Issue by dzg** [sveinbjornt/Platypus#153]
This is very cool ... but I see that in my final `.app` bundle, my original python source code is there in `script`.

Is there any way to compile or hide the source code?

Thanks!

**Comment by sveinbjornt** [comment]
There used to be an option to obfuscate the script back in the days, but I got rid of it because it was "security theatre". As long as the script is fed to the Python interpreter as plain text, getting the original source code is trivial for anyone with a modest understanding of how these things work.
