### ISSUE TITLE
Create .app that runs truly UI-less

### ISSUE THREAD

**Issue by peetinc** [sveinbjornt/Platypus#162]
**Feature Enhancement:** When "Interface None" is selected do not call any UI elements that will stop the Platypus created app from executing as a LaunchDaemon or LaunchAgent in the LoginWindow context. Consider an argument that can be passed to the app binary of any "Interface" type that would disable any UI calls.

**Use Case:** Because of PPPC controls using 'naked' shell scripts as launchd programs ends up with endusers or admins being prompted to allow the interpreter (zsh, bash, sh, etc) access to PPPC's like Full Disk Access, Screen Recording or Accessibility because the final binary that was launched is a child of the interpreter. To get around this I've built and signed launchd-executed apps with Platypus that no longer work with 10.15 because of (maybe documented) changes.

**Background:** Before 10.15, launchd would happily run Platypus created apps as LaunchDaemons and LoginWindow LaunchAgents. As of 10.15.0 if ../MyApp.app/Contents/MacOS/MyApp is called at boot by launchd, the app will start, but it will never execute the "../Resources/script".  The same failure happens with with an AppleScript.app wrapped around a shell script. Using "do shell script" and setting LSUIElement to true in Info.plist one ends up with an app bundle similar to a Platypus created app. The same AppleScript.app that fails with a boot up launchd in 10.15 works in 10.14 and 10.13. 

As an aside, a global LaunchAgent configured to run in the LoginWindow context will happily run on logout, just not on startup. Something that made this confusing to troubleshoot.

I'm not sure how to debug it more thoroughly for you, but I'm happy to do whatever you might need. In the mean time I've "written" a hack of an objective-C "command line tool" and dropped into an app bundle, so I do know that having no UI calls in a .app does work. But boy is it ugly.

Thanks for all you do.

**Comment by sveinbjornt** [comment]
Platypus as a "thing" is becoming ever more difficult, with Apple shutting down the platform with code signing, entitlements, etc. I'll see what I can do once I find time to work on Platypus, but I cannot make any promises. I'd love for Platypus to be useful out of the box like it was in the old days, but the OS environment is changing faster than I can keep up with.

**Comment by JayBrown** [comment]
Not sure if this is what you're looking for, but you're right: global agents can't be run as login item; that's what user agents are for. But those don't run with privilege escalation. So you either have to find a way to call a global daemon from a user agent at login, or hold/pause a global daemon until user login:

(a) you can have the login agent (user) write a file to a specific directory, which in turn is watched by global daemon (root) with the WatchPaths key, and the daemon will start as soon as that file appears.

(b) you start the global daemon during boot, and have it wait until the user has actually logged in, e.g. like so:

```
while true
do
	whoinfo=$(who | grep "console")
	if [[ $whoinfo ]] ; then
		loggeduser=$(echo "$whoinfo" | awk '{print $1}')
		echo "Logged user detected: $loggeduser"
		break
	fi
	sleep 1
done
```

and only when there's a logged in user do you start the Platypus app, or a global agent etc.

(c) To circumvent TCC prompts for shell script (or a script within a Platypus app), you can also use the `fdautil` tool that's part of SomaZone's LaunchControl, e.g. like so:

```
/usr/local/bin/fdautil exec /foo/bar/baz.sh
```

If `fdautil` is on your Full Disk Access List, then your scripts are good with regards to accessing TCC-protected locations.

However, I haven't tested `fdautil` with a Platypus app/script yet.

Note 1: afaik this wouldn't solve the problem with camera access and accessibility prompts for the interpreter, but maybe a helper tool similar to `fdautil` can be created for the next Platypus upgrade, one that can be granted access to camera & accessibility features, and to TCC-protected folders, either via individual prompt or by Full Disk Access. (The user would just have to launch the Platypus app once after installation to register it.) However, this would need to happen on a per-Platypus-app basis, tied to the Platypus-app's Bundle ID, otherwise it would be a security/privacy risk.

Note 2: as for camera access via shell scripts, I have had no problems on Mojave, even before user login, but I haven't tested this on Catalina yet. The only thing I've successfully tested is an Automator workflow, exported as a code-signed app. It doesn't work with AppleScript apps exported from ScriptEditor, but with workflows-as-apps it has worked fine. (Maybe a similar solution will work in your case too.)
