### ISSUE TITLE
Adding new images for use?

### ISSUE THREAD

**Issue by s22-tech** [sveinbjornt/Platypus#198]
Is it possible to add our own images to Platypus for us to use when building apps?  There are currently 3 embedded images - Default Icon, Installer, and generic Application - but it would be nice to add our own to those defaults, as well.

(I know we can use any graphic using the gear icon, I was just wondering if this was possible.)

**Comment by sveinbjornt** [comment]
There's currently no way to add to the icon presets without changing code. But you can drag and drop an icns or image file, or, as you noted, select an icon via the contextual menu that pops upp when pressing the gear icon.

If you are automating app creation, I recommend using the command line tool rather than the GUI app.
