### ISSUE TITLE
I can't even run it

### ISSUE THREAD

**Issue by alvinhowse** [sveinbjornt/Platypus#283]
So, I went and tried to run it, but couldn't run it because:

![Screenshot 2024-12-23 at 16 45 23](https://github.com/user-attachments/assets/156165b9-c88b-4beb-b6c6-dcc4a74bad9c)

I hope the repository owner hasn't just made a bunch of malware.

**Comment by Bill-Costa** [comment]
*> So, I went and tried to run it, but couldn't run it because:*
"Platypus.app" can't be opened because Apple cannot check it for malicious
software.

Here's what you need to do on the latest macOS versions:

https://support.apple.com/en-mn/guide/mac-help/mchleab3a043/mac

...BC

-- 
***@***.***
Just another geek in Northern New England, USA.

**Comment by sveinbjornt** [comment]
No malware going on, just Apple's paranoid macOS security policies. Platypus is developer-signed but not verified by Apple or distributed in their shitty App Store.

**Comment by alvinhowse** [comment]
I am having trouble running it, because I do not want to affect all of the users of the Mac.

**Comment by alvinhowse** [comment]
I am now on Windows and don't use Platypus anymore
