### ISSUE TITLE
Feature request: Allow to launch binary scripts with arguments

### ISSUE THREAD

**Issue by nekopep** [sveinbjornt/Platypus#47]
Hello,
I'm creating some binary python scripts with python and pyinstaller. The result is a one file binary file.
I want to drag and drop file on my result binary so that it see the file as first or second argument. Sadly I haven't found any way so far to do that :/
I've tried interpreter /bin/sh + '-exec' + binary_name + file but file argument is not seen as, to work, it needs /bin/sh -exec "binary_name file" and there is no way to put " at the end of the line :/
So if you have any hint :)
This would be a very good feature since pyinstaller does not support drag and drop freature and platypus is quite efficient in this area.

**Comment by MickCrozier** [comment]
+1

**Comment by sveinbjornt** [comment]
Could you explain this better? Maybe send me an example?

**Comment by nekopep** [comment]
Hi sveinbjornt,

Let's take this simple file main.c ->
#include <stdio.h>
int main(int argc, char** argv)
{
   int i;
   for (i=0;i<argc;i++)
     printf("arg %d:%s\n",i,argv[i]);
}

#gcc main.c -o main
#chmod +x main
#./main 1 2 3 4
arg 0:./main
arg 1:1
arg 2:2
arg 3:3
arg 4:4

So now, I would like to be able to launch this "main" "script" and to drag and drop on it several files.
Because Platypus only handle calling /bin/sh etc..., I managed to workaround this setting platypus launch /bin/bash with arg "-exec":
![capture d ecran 2015-06-16 a 00 47 48](https://cloud.githubusercontent.com/assets/2825997/8172498/66df4464-13c1-11e5-9c4a-a3803dbdb274.png)
![capture d ecran 2015-06-16 a 00 48 40](https://cloud.githubusercontent.com/assets/2825997/8172507/803e691c-13c1-11e5-8141-1ab048b8c704.png)
 From my experiments the only issue is just to allow platypus to add quotes (") after -exec and the end of the launching  cmd:

/bin/sh -exec "./main file1 file2"

Currenlty platypus does:
/bin/sh -exec "./main" file1 file2 
So ./main does not see any arguments.

Another way to workaround this would be to allow launch an executabel instead of a script, but not sure it is possible :)

**Comment by nekopep** [comment]
By the way, I can send you an executable if you want.

**Comment by sveinbjornt** [comment]
Ah, I understand your problem. Let me get back to you on that.

**Comment by sveinbjornt** [comment]
Why not have a shell script execute you python scripts, e.g.

#!/bin/sh

python myPythonScript.py $@

or something to that effect.

**Comment by tjnycum** [comment]
I have the same request as described in the title, but in my case I need to launch binaries that I didn't compile from scripts (so I can't do as you just suggested).

Several times I've had a binary that isn't wrapped in an app bundle—[Meld](http://meldmerge.org/) [built using homebrew](https://github.com/Homebrew/homebrew-x11/blob/master/meld.rb), for example—and I'd like to use Platypus to easily make such a wrapper. Currently there are two options: make a trivial little shell script wrapper for every such binary (and settle for the unnecessary interpreter process), or use the "-exec" workaround described by @nekopep (if you don't need to pass any arguments to the binary). Platypus is *so close* to also filling our need (calling a binary, perhaps with arguments) natively (i.e. without wrapper script) and its existing ability to capture stdout in a window would fit perfectly with this. It could easily handle both its current work (scripts) and binaries by generalizing itself just a *little bit*, (mostly in the UI, since it's already calling a binary with arguments).

What I propose:
Give the option of launching an arbitrary binary instead of one of the script interpreters. The argument entry interface can do double-duty. If an interpreter is selected, arguments can be entered for either the interpreter or the script. If an arbitrary binary is selected, the only difference is that there is no script, so any arguments have to go to the binary.

If you're amenable to the idea, but not sure how you could generalize it without making the UI less user-friendly (to those who don't think of an interpreter as just another binary and the script being an argument), I can think about and propose specific changes to the interface (smaller ones obviously being better).

**Comment by sveinbjornt** [comment]
This is a good idea. I'll add a "Custom Binary" feature to the Platypus 5.1 roadmap.

**Comment by tewe** [comment]
This would be nice, but really isn't necessary. One more Bash process to pass through the arguments doesn't hurt anybody, and even if, both Perl and Python wrap the exec system call, so your binary can replace the interpreter in memory.

**Comment by arvindsree** [comment]
This is very much required. In my use case, I have a GUI application. I am using a script to call the application. So if I use platypus to convert the script to app, I get two windows, a dummy platypus app window(although can be hidden with no interface) and my actual application windows. Because of this I cannot use the "keep in dock" feature of Mac. (Which docks the platypus window)

**Comment by leetom** [comment]
Looking forward for "Custom Binary" feature, but haven't seen this on 5.1

**Comment by phloggu** [comment]
Have you tried it with
`bash -c <custom_bin>`
?

**Comment by arvindsree** [comment]
no phloggu. If you use "bash -c", the process that would be run would be bash which would launch a new window. Again the "Keep in dock" feature of mac would fail, as this is opened in a seperate window

**Comment by sveinbjornt** [comment]
After some consideration, I've decided that I won't implement this feature. If you want to create an application bundle around a binary, create an application bundle around a binary. The documentation on how to do this is out there, and Platypus-generated apps could serve as an example. 

Implementing such functionality would make Platypus more confusing and extend and change the fundamental purpose of the app.

**Comment by tjnycum** [comment]
@sveinbjornt: As I understand it Platypus intends to make it easy to create application bundles around scripts. I'm having trouble understanding how extending this to binaries amounts to a show-stopping change of purpose, especially given that the current app bundles around scripts already _are_ app bundles around binaries.

The reason for requesting this instead of simply creating application bundles around binaries from scratch is the exact same reason for Platypus existing in the first place: convenience. You've already created very useful functionality (e.g. capturing output, droppable input) that'd be just as useful for binaries as for scripts.

Before you commit to an about-face on this, as I requested [above](#issuecomment-120248041), would you _please_ give us an opportunity to at least suggest ways to mitigate the confusion you see this slight generalization as creating? If there are actually other concerns, would you please share them?

**Comment by stephane-archer** [comment]
Does anyone found a solution? I can't add the -exec option and make it work. I don't get why platypus required you to use an interpreter. My program is written in Go...
