### ISSUE TITLE
Make .platypus files movable/portable/exchangable

### ISSUE THREAD

**Issue by stuporglue** [sveinbjornt/Platypus#49]
It would be convenient to be able to move a .platypus file or to be able to share it with someone. The plist has hard coded file paths right now which means if I move my project folder I have to set up Platypus again. 

If it's something baked into OSX's plsit creation, it might be nice to detect when the script and icon specified can't be found and give the user an option to select a new base directory for them.

**Comment by sveinbjornt** [comment]
This is a tougher issue than one might think. There are basically two strategies:

a) Make profile reference local files, absolute paths. This enables people to change the script/icon files and the profile still works.

b) Embed all data required for the app into the profile. This means that profiles can be shared, but will not update when the source icon/script files change. Also makes it more of an issue to edit profile data, since it has been embedded and is not associated with known files.

I've gone with strategy a) so far but I'm open to arguments in favour of other solutions.

**Comment by stuporglue** [comment]
(A) probably make more sense between the two. I tend to work with a single directory for each project, and all my resources (and so, all my paths) are in that directory. Not everyone works like that though and Platypus is nice and simple and complicating with this would probably not make sense. 

I think what I'll do is make a Platypus droplet that accepts a .platypus file and replaces all paths with the path to the .platypus file's directory.

**Comment by stuporglue** [comment]
Oops. Didn't mean to close this, sorry.
