### ISSUE TITLE
Issue with status menu interface apps

### ISSUE THREAD

**Issue by Corgi** [sveinbjornt/Platypus#58]
Running version 5.1; also occurs on 5.0.

I've been experiencing a strange issue when building a status menu interface application. The application builds fine, but when launched, the script does not actually seem to execute until I click on the menu icon for it. Upon doing this, the script launches, but then the menu immediately beachballs, and locks out all keyboard input except for alt-tab. (When force-quit from the Activity Monitor behavior returns to normal, though the script continues to run.)

The script in question is a very simple node.js command ("npm start") that launches a chatbot program. Additionally, this issue only occurs when the script executes successfully; if the script encounters an error it will return output like this:

![image](https://cloud.githubusercontent.com/assets/1316783/12301761/5c7c45cc-b9e7-11e5-8542-5adbf698003f.png)

These are my options within Platypus when building:

![image](https://cloud.githubusercontent.com/assets/1316783/12301811/a02b7cc0-b9e7-11e5-933d-412d7ad88c45.png)

When built as a text window, the app works as expected.

![image](https://cloud.githubusercontent.com/assets/1316783/12301898/1330a68c-b9e8-11e5-89d6-f3b1140c0797.png)

It's entirely possible I'm doing something wrong, as I'm very, very new to node/npm.

**Comment by sveinbjornt** [comment]
This has to do with how the Status Menu interface type works and is expected behaviour.  

When you click the status item, the script is executed and the main thread locks until the script is done executing. The output from the script is then presented line for line as menu items.  Your problem is that your script doesn't exit, hence the app will wait indefinitely for the process to be done executing.

The documentation could be more clear on this issue. I'll be sure to update it for the next release.

**Comment by fabiosoft** [comment]
Same problem for me, good explaination by @Corgi ... so much thanks!

I really love the easy feel of this project!

I also have a non ending script, are there some alternative to keep it running properly without blocking the entire menu item? I have a socket listening for incoming messages...
