### ISSUE TITLE
Trying to get generated app to open files from Finder

### ISSUE THREAD

**Issue by PacoH** [sveinbjornt/Platypus#74]
I generated an app that wraps a bash script that opens media files in `mplayer`, using `Platypus 5.1`. I associated `mp4` files with the app but `cmd-o` or double-clicking a file in `Finder` only opens `mplayer` in a text window, showing keyboard shortcuts. The file path is not passed to the script. I can't find anything about doing this. I can open a file from the command line, using the app's binary's path and providing the file path, but there is no advantage to that. Is there any way to pass the file path from the `Finder`, and opening it with the app in the normal manner?

The simple script I used is:

    /usr/local/bin/mplayer -vf screenshot "$@"

I attached the saved profile of the app.

[MyMplayer.platypus.zip](https://github.com/sveinbjornt/Platypus/files/338379/MyMplayer.platypus.zip)

**Comment by tewe** [comment]
"Accepts dropped items" is not enabled in your profile, so Platypus discards any files the Finder passes to it. Since mplayer isn't getting any files, it displays its help text.

Actually Finder shouldn't allow you to associate files with an app that doesn't accept them. Maybe that's a bug in Platypus' defaults.

And I think you should use mpv in favor of mplayer ;)
