### ISSUE TITLE
How to update web view?

### ISSUE THREAD

**Issue by vkuznet** [sveinbjornt/Platypus#96]
Hi, I want to feed an HTML output into web view on a periodic basis.. The problem is that I want to update either update current HTML context or replace existing parts (via JS). Is it possible to do?

**Comment by sveinbjornt** [comment]
JavaScript should work just fine to update stuff. But once the script is done running, that's it.

**Comment by vkuznet** [comment]
That's what I'm trying to understand. I want to push new content on a periodic
basis. I tried using current web view and what I get is continuous append
to web window, i.e. it start growing such that if I resize window I can see
previous content. What I want is to "clear" window with every push, like
terminal clear command.

**Comment by sveinbjornt** [comment]
This is not possible at the moment, but perhaps implementing a REFRESH command in the output or something could do the trick.

**Comment by sveinbjornt** [comment]
Will implement this in the next version.

**Comment by thenameisdavid** [comment]
If I correctly understand the issue here, you should be able to accomplish this using the PHP interpreter to run an AJAX request. I haven't tried it myself, but so far I managed to actively fetch and pause multiple http streams using the PHP interpreter using Javascript and the Python interpreter specifically to render JSON content from Google Maps. BTW, Svein, I love your application. Managed to modify the Main nib file in XCode in order to make render the Webview into full screen.
